version: '3.8'



services:
  client:
    build: ./src/client
    ports:
      - "3000:3000"  # This should map the local port 3000 to the container's port 3000
    volumes:
      - ./src/client:/usr/src/app
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/ai-central-db
    env_file:
      - .env  # Docker Compose will load environment variables from this file
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: